name: Jellyfish Scraper

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    
    concurrency:
      group: scraper
      cancel-in-progress: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install playwright requests python-dotenv
          playwright install chromium

      - name: Run script
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: python medusometer.py